### ISSUE TITLE
IoTDatasetProcessed Request

### ISSUE THREAD

**Issue by kanglinew** [notem/iot-device-classification#1]
Dear author, could I ask for IoTDatasetProcessed related data from you? Thank you very much!

**Comment by notem** [comment]
The author's dataset is available [here](https://iotanalytics.unsw.edu.au/iottraces.html).

PS: I should note that I am _not_ the author of the original work. This project is just a re-implementation of the technique pipeline described in their paper.

**Comment by kanglinew** [comment]
谢谢来信，已收到！祝好：）
